### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by richrumble** [nahamsec/CMSFuzz#1]
Add Sharepoint to your list :)
http://social.technet.microsoft.com/wiki/contents/articles/25431.sharepoint-2013-the-15-hive-and-other-important-directories.aspx#Folder_Structure 
http://carnal0wnage.attackresearch.com/2012/05/from-low-to-pwned-6-sharepoint.html
(see also logic and dir's from the now defunct SkipFish 
https://code.google.com/p/skipfish/source/browse/#svn%2Ftrunk%2Fdictionaries)
I still use skipfish for this particular attack, it's great at finding dirs that other tools don't.

**Comment by nahamsec** [comment]
This will be added to the next update with a few extra options as well. Thanks for reaching out!
